spark.master                      spark://spark-master:7077
spark.submit.deployMode           client
spark.driver.memory               3g
spark.executor.memory             2g
spark.executor.cores              2
spark.local.dir                   /tmp/spark-local
spark.sql.shuffle.partitions      16
spark.sql.adaptive.enabled        true
